# Generated by Django 5.2.12 on 2026-04-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0042_workoutfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietician',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dietician',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DieticianRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.dietician')),
            ],
            options={
                'unique_together': {('customer', 'dietician')},
            },
        ),
    ]
